// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartFleet.Backend.Data;

#nullable disable

namespace SmartFleet.Backend.Data.Migrations
{
    [DbContext(typeof(SmartFleetDbContext))]
    [Migration("20260918083624_AddBreakdownReportAndFailureCatalog")]
    partial class AddBreakdownReportAndFailureCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartFleet.Backend.Models.BreakdownReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DiagnosisResultJson")
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ReportedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SymptomCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReportedById");

                    b.HasIndex("Status");

                    b.ToTable("BreakdownReports", (string)null);
                });

            modelBuilder.Entity("SmartFleet.Backend.Models.FailureCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedRepairHours")
                        .HasColumnType("integer");

                    b.Property<string>("LikelyPart")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SymptomCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SymptomKeyword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SymptomKeyword");

                    b.ToTable("FailureCatalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            EstimatedRepairHours = 2,
                            LikelyPart = "Drive Motor Unit",
                            Severity = "High",
                            SymptomCategory = "MotorOverheating",
                            SymptomKeyword = "motor overheating"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            EstimatedRepairHours = 3,
                            LikelyPart = "Wheel Bearing & Axle Assembly",
                            Severity = "High",
                            SymptomCategory = "WheelJam",
                            SymptomKeyword = "wheel jam"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            EstimatedRepairHours = 2,
                            LikelyPart = "Drive Motor Unit",
                            Severity = "High",
                            SymptomCategory = "MotorOverheating",
                            SymptomKeyword = "grinding noise"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            EstimatedRepairHours = 1,
                            LikelyPart = "Front LiDAR / Ultrasonic Array",
                            Severity = "Medium",
                            SymptomCategory = "SensorFault",
                            SymptomKeyword = "sensor fault"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            EstimatedRepairHours = 4,
                            LikelyPart = "Lithium Iron Phosphate Battery Pack",
                            Severity = "Critical",
                            SymptomCategory = "BatteryDegradation",
                            SymptomKeyword = "battery degradation"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            EstimatedRepairHours = 1,
                            LikelyPart = "Telemetry Wi-Fi / UWB Module",
                            Severity = "Low",
                            SymptomCategory = "SensorFault",
                            SymptomKeyword = "communication loss"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            EstimatedRepairHours = 3,
                            LikelyPart = "Electromagnetic Brake Caliper",
                            Severity = "Critical",
                            SymptomCategory = "WheelJam",
                            SymptomKeyword = "brake failure"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            EstimatedRepairHours = 2,
                            LikelyPart = "Steering Actuator Servo",
                            Severity = "High",
                            SymptomCategory = "WheelJam",
                            SymptomKeyword = "steering lock"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            EstimatedRepairHours = 2,
                            LikelyPart = "Power Distribution Board (PDB)",
                            Severity = "High",
                            SymptomCategory = "BatteryDegradation",
                            SymptomKeyword = "overvoltage"
                        });
                });

            modelBuilder.Entity("SmartFleet.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartFleet.Backend.Models.BreakdownReport", b =>
                {
                    b.HasOne("SmartFleet.Backend.Models.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
