import React, { useState, useEffect, useCallback } from 'react';
import {
  Send,
  Plus,
  Search,
  RefreshCw,
  Cpu,
  CheckCircle2,
  Clock,
  X,
  ArrowRight,
  ShieldCheck,
  Radio,
  SlidersHorizontal,
  ChevronLeft,
  ChevronRight,
} from 'lucide-react';
import { dispatchApi } from '../api/dispatchApi';
import {
  DispatchRequest,
  CreateDispatchRequestInput,
  DispatchRequestStatus,
  MissionPlannerOutput,
} from '../types/dispatch';
import { EmptyState } from '../components/Common/EmptyState';
import { LoadingSpinner } from '../components/Common/LoadingSpinner';
import { ErrorAlert } from '../components/Common/ErrorAlert';

export const DispatchRequests: React.FC = () => {
  const [requests, setRequests] = useState<DispatchRequest[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Filters & Pagination
  const [search, setSearch] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<string>('');
  const [zoneFilter, setZoneFilter] = useState<string>('');
  const [page, setPage] = useState<number>(1);
  const [totalPages, setTotalPages] = useState<number>(1);
  const [totalCount, setTotalCount] = useState<number>(0);

  // Modals & Active Items
  const [isCreateOpen, setIsCreateOpen] = useState<boolean>(false);
  const [isPlanModalOpen, setIsPlanModalOpen] = useState<boolean>(false);
  const [activePlan, setActivePlan] = useState<MissionPlannerOutput | null>(null);
  const [activeRequestId, setActiveRequestId] = useState<string | null>(null);
  const [generatingPlanId, setGeneratingPlanId] = useState<string | null>(null);
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);

  // Form State
  const [sourceZone, setSourceZone] = useState<string>('WarehouseA-DockA1');
  const [destinationZone, setDestinationZone] = useState<string>('WarehouseA-DockB3');
  const [cargoType, setCargoType] = useState<string>('Fragile');
  const [priority, setPriority] = useState<string>('High');
  const [timeWindow, setTimeWindow] = useState<string>(() => {
    const d = new Date();
    d.setHours(d.getHours() + 2);
    return d.toISOString().slice(0, 16);
  });
  const [submitting, setSubmitting] = useState<boolean>(false);

  const fetchRequests = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await dispatchApi.getDispatchRequests({
        search: search.trim() || undefined,
        status: statusFilter || undefined,
        zone: zoneFilter.trim() || undefined,
        page,
        pageSize: 10,
        sortBy: 'CreatedAt',
        sortDescending: true,
      });

      setRequests(res.items);
      setTotalPages(res.totalPages);
      setTotalCount(res.totalCount);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to load dispatch requests. Please retry.');
    } finally {
      setLoading(false);
    }
  }, [search, statusFilter, zoneFilter, page]);

  useEffect(() => {
    fetchRequests();
  }, [fetchRequests]);

  const handleCreateSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setSubmitting(true);
      setError(null);

      const payload: CreateDispatchRequestInput = {
        sourceZone,
        destinationZone,
        cargoType,
        priority,
        preferredTimeWindow: new Date(timeWindow).toISOString(),
      };

      const newRequest = await dispatchApi.createDispatchRequest(payload);
      setActionSuccess(`Order #${newRequest.id.slice(0, 8)} created successfully.`);
      setIsCreateOpen(false);
      setPage(1);
      fetchRequests();

      setTimeout(() => setActionSuccess(null), 5000);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to submit dispatch request.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleGeneratePlan = async (request: DispatchRequest) => {
    try {
      setGeneratingPlanId(request.id);
      setError(null);

      const planResult = await dispatchApi.generatePlan(request.id);
      setActivePlan(planResult);
      setActiveRequestId(request.id);
      setIsPlanModalOpen(true);
      setActionSuccess(`Mission plan generated by MissionPlannerAgent for #${request.id.slice(0, 8)}.`);

      // Refresh list to show updated status
      fetchRequests();

      setTimeout(() => setActionSuccess(null), 5000);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to generate mission plan.');
    } finally {
      setGeneratingPlanId(null);
    }
  };

  const handleViewExistingPlan = (request: DispatchRequest) => {
    if (request.latestPlan) {
      setActivePlan(request.latestPlan);
      setActiveRequestId(request.id);
      setIsPlanModalOpen(true);
    }
  };

  const getStatusBadge = (status: DispatchRequestStatus) => {
    switch (status) {
      case 'Pending':
        return <span className="badge" style={{ background: 'rgba(245, 158, 11, 0.15)', color: '#fbbf24', border: '1px solid rgba(251, 191, 36, 0.3)' }}>Pending</span>;
      case 'Planned':
        return <span className="badge" style={{ background: 'rgba(56, 189, 248, 0.15)', color: '#38bdf8', border: '1px solid rgba(56, 189, 248, 0.3)' }}>Planned</span>;
      case 'AwaitingApproval':
        return <span className="badge" style={{ background: 'rgba(139, 92, 246, 0.15)', color: '#c084fc', border: '1px solid rgba(139, 92, 246, 0.3)' }}>Awaiting Approval</span>;
      case 'Approved':
        return <span className="badge" style={{ background: 'rgba(16, 185, 129, 0.15)', color: '#34d399', border: '1px solid rgba(16, 185, 129, 0.3)' }}>Approved</span>;
      case 'InTransit':
        return <span className="badge" style={{ background: 'rgba(2, 132, 199, 0.15)', color: '#60a5fa', border: '1px solid rgba(96, 165, 250, 0.3)' }}>In Transit</span>;
      case 'Completed':
        return <span className="badge" style={{ background: 'rgba(16, 185, 129, 0.2)', color: '#10b981', border: '1px solid #10b981' }}>Completed</span>;
      case 'Rejected':
      case 'Failed':
        return <span className="badge" style={{ background: 'rgba(239, 68, 68, 0.15)', color: '#f87171', border: '1px solid rgba(239, 68, 68, 0.3)' }}>{status}</span>;
      default:
        return <span className="badge">{status}</span>;
    }
  };

  const getPriorityBadge = (p: string) => {
    switch (p.toLowerCase()) {
      case 'critical':
        return <span className="badge" style={{ background: 'rgba(239, 68, 68, 0.2)', color: '#ef4444', border: '1px solid #ef4444' }}>Critical</span>;
      case 'high':
        return <span className="badge" style={{ background: 'rgba(245, 158, 11, 0.15)', color: '#f59e0b', border: '1px solid #f59e0b' }}>High</span>;
      case 'medium':
        return <span className="badge" style={{ background: 'rgba(56, 189, 248, 0.15)', color: '#38bdf8', border: '1px solid rgba(56, 189, 248, 0.3)' }}>Medium</span>;
      default:
        return <span className="badge" style={{ background: 'rgba(148, 163, 184, 0.15)', color: '#94a3b8', border: '1px solid rgba(148, 163, 184, 0.3)' }}>Low</span>;
    }
  };

  return (
    <div>
      {/* Top Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.75rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1 style={{ fontSize: '1.85rem', fontWeight: 800, marginBottom: '0.25rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <Send size={26} color="var(--primary-light)" />
            Dispatch Request Pipeline
          </h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem' }}>
            Manage warehouse transport orders, inspect mission plans, and coordinate multi-agent rover scheduling.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button className="btn btn-secondary" onClick={fetchRequests} title="Refresh orders">
            <RefreshCw size={16} />
            Refresh
          </button>
          <button className="btn btn-primary" onClick={() => setIsCreateOpen(true)}>
            <Plus size={18} />
            New Dispatch Order
          </button>
        </div>
      </div>

      {/* Action Notification */}
      {actionSuccess && (
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.75rem',
          padding: '0.85rem 1.25rem',
          borderRadius: 'var(--radius-sm)',
          background: 'rgba(16, 185, 129, 0.15)',
          border: '1px solid rgba(16, 185, 129, 0.3)',
          color: '#34d399',
          marginBottom: '1.25rem'
        }}>
          <CheckCircle2 size={18} />
          <span>{actionSuccess}</span>
        </div>
      )}

      {/* Error Alert */}
      {error && <ErrorAlert message={error} onDismiss={() => setError(null)} />}

      {/* Search & Filter Toolbar */}
      <div className="glass-card" style={{ padding: '1rem 1.25rem', marginBottom: '1.5rem', display: 'flex', gap: '1rem', flexWrap: 'wrap', alignItems: 'center' }}>
        <div style={{ flex: '1 1 240px', position: 'relative' }}>
          <Search size={16} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
          <input
            type="text"
            className="form-input"
            style={{ paddingLeft: '2.5rem' }}
            placeholder="Search zones, cargo, priority, or operator..."
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setPage(1);
            }}
          />
        </div>

        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', flexWrap: 'wrap' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <SlidersHorizontal size={16} color="var(--text-muted)" />
            <select
              className="form-input"
              style={{ width: 'auto', padding: '0.65rem 1rem' }}
              value={statusFilter}
              onChange={(e) => {
                setStatusFilter(e.target.value);
                setPage(1);
              }}
            >
              <option value="">All Statuses</option>
              <option value="Pending">Pending</option>
              <option value="Planned">Planned</option>
              <option value="AwaitingApproval">Awaiting Approval</option>
              <option value="Approved">Approved</option>
              <option value="InTransit">In Transit</option>
              <option value="Completed">Completed</option>
              <option value="Rejected">Rejected</option>
              <option value="Failed">Failed</option>
            </select>
          </div>

          <input
            type="text"
            className="form-input"
            style={{ width: '180px', padding: '0.65rem 1rem' }}
            placeholder="Filter by zone..."
            value={zoneFilter}
            onChange={(e) => {
              setZoneFilter(e.target.value);
              setPage(1);
            }}
          />

          {(search || statusFilter || zoneFilter) && (
            <button
              className="btn btn-secondary"
              style={{ padding: '0.65rem 0.85rem' }}
              onClick={() => {
                setSearch('');
                setStatusFilter('');
                setZoneFilter('');
                setPage(1);
              }}
            >
              Clear
            </button>
          )}
        </div>
      </div>

      {/* Main Content Area */}
      {loading ? (
        <div style={{ padding: '4rem 0', display: 'flex', justifyContent: 'center' }}>
          <LoadingSpinner text="Fetching dispatch orders..." />
        </div>
      ) : requests.length === 0 ? (
        <EmptyState
          icon={<Send size={36} color="var(--primary-light)" />}
          title="No Dispatch Requests Found"
          description={
            search || statusFilter || zoneFilter
              ? "No dispatch orders match the selected filters. Try broadening your criteria."
              : "No dispatch orders have been submitted yet. Submit a new order to trigger the Mission Planner Agent."
          }
          actionLabel="Submit First Dispatch Order"
          onAction={() => setIsCreateOpen(true)}
        />
      ) : (
        <>
          <div className="table-container">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Order ID</th>
                  <th>Route (Pickup &rarr; Dropoff)</th>
                  <th>Cargo</th>
                  <th>Priority</th>
                  <th>Time Window</th>
                  <th>Status</th>
                  <th>Submitted</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {requests.map((req) => (
                  <tr key={req.id}>
                    <td>
                      <span style={{ fontFamily: 'monospace', fontWeight: 600, color: 'var(--primary-light)' }}>
                        #{req.id.slice(0, 8)}
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 500 }}>
                        <span>{req.sourceZone}</span>
                        <ArrowRight size={14} color="var(--text-muted)" />
                        <span style={{ color: 'var(--primary-light)' }}>{req.destinationZone}</span>
                      </div>
                    </td>
                    <td>
                      <span style={{ fontWeight: 500 }}>{req.cargoType}</span>
                    </td>
                    <td>{getPriorityBadge(req.priority)}</td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                        <Clock size={13} />
                        {new Date(req.preferredTimeWindow).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </div>
                    </td>
                    <td>{getStatusBadge(req.status)}</td>
                    <td style={{ color: 'var(--text-faint)', fontSize: '0.85rem' }}>
                      {new Date(req.createdAt).toLocaleDateString([], { month: 'short', day: 'numeric' })}
                    </td>
                    <td style={{ textAlign: 'right' }}>
                      <div style={{ display: 'inline-flex', gap: '0.5rem' }}>
                        {req.status === 'Pending' && (
                          <button
                            className="btn btn-primary"
                            style={{ padding: '0.45rem 0.85rem', fontSize: '0.8rem' }}
                            onClick={() => handleGeneratePlan(req)}
                            disabled={generatingPlanId === req.id}
                          >
                            {generatingPlanId === req.id ? (
                              <>
                                <span className="spinner" style={{ width: '14px', height: '14px' }} />
                                Planning...
                              </>
                            ) : (
                              <>
                                <Cpu size={14} />
                                Generate Plan
                              </>
                            )}
                          </button>
                        )}

                        {req.latestPlan && (
                          <button
                            className="btn btn-secondary"
                            style={{ padding: '0.45rem 0.85rem', fontSize: '0.8rem' }}
                            onClick={() => handleViewExistingPlan(req)}
                          >
                            <ShieldCheck size={14} color="var(--primary-light)" />
                            View Checklist
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Pagination Controls */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '1.25rem', padding: '0 0.5rem' }}>
            <span style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>
              Showing {requests.length} of {totalCount} requests (Page {page} of {Math.max(1, totalPages)})
            </span>

            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <button
                className="btn btn-secondary"
                style={{ padding: '0.5rem 0.85rem' }}
                disabled={page <= 1}
                onClick={() => setPage((p) => Math.max(1, p - 1))}
              >
                <ChevronLeft size={16} />
                Previous
              </button>
              <button
                className="btn btn-secondary"
                style={{ padding: '0.5rem 0.85rem' }}
                disabled={page >= totalPages}
                onClick={() => setPage((p) => p + 1)}
              >
                Next
                <ChevronRight size={16} />
              </button>
            </div>
          </div>
        </>
      )}

      {/* Modal 1: Create Dispatch Request Form */}
      {isCreateOpen && (
        <div className="modal-overlay" onClick={() => !submitting && setIsCreateOpen(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '1rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <Send size={22} color="var(--primary-light)" />
                <h2 style={{ fontSize: '1.35rem', fontWeight: 700 }}>Submit Dispatch Request</h2>
              </div>
              <button
                style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}
                onClick={() => setIsCreateOpen(false)}
              >
                <X size={20} />
              </button>
            </div>

            <form onSubmit={handleCreateSubmit}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div className="form-group">
                  <label className="form-label">Source Zone (Pickup)</label>
                  <input
                    type="text"
                    required
                    className="form-input"
                    value={sourceZone}
                    onChange={(e) => setSourceZone(e.target.value)}
                    placeholder="e.g. WarehouseA-DockA1"
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Destination Zone (Dropoff)</label>
                  <input
                    type="text"
                    required
                    className="form-input"
                    value={destinationZone}
                    onChange={(e) => setDestinationZone(e.target.value)}
                    placeholder="e.g. WarehouseA-DockB3"
                  />
                </div>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div className="form-group">
                  <label className="form-label">Cargo Classification</label>
                  <select
                    className="form-input"
                    value={cargoType}
                    onChange={(e) => setCargoType(e.target.value)}
                  >
                    <option value="Fragile">Fragile Electronics</option>
                    <option value="Standard">Standard Pallet</option>
                    <option value="Hazmat">Hazmat Materials</option>
                    <option value="Refrigerated">Refrigerated Goods</option>
                    <option value="Heavy Machinery">Heavy Machinery Component</option>
                  </select>
                </div>

                <div className="form-group">
                  <label className="form-label">Priority Level</label>
                  <select
                    className="form-input"
                    value={priority}
                    onChange={(e) => setPriority(e.target.value)}
                  >
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                    <option value="Critical">Critical</option>
                  </select>
                </div>
              </div>

              <div className="form-group">
                <label className="form-label">Preferred Time Window (UTC Target)</label>
                <input
                  type="datetime-local"
                  required
                  className="form-input"
                  value={timeWindow}
                  onChange={(e) => setTimeWindow(e.target.value)}
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginTop: '1.75rem' }}>
                <button
                  type="button"
                  className="btn btn-secondary"
                  disabled={submitting}
                  onClick={() => setIsCreateOpen(false)}
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary" disabled={submitting}>
                  {submitting ? (
                    <>
                      <span className="spinner" style={{ width: '16px', height: '16px' }} />
                      Submitting Order...
                    </>
                  ) : (
                    <>
                      <Send size={16} />
                      Submit Order
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Modal 2: Mission Plan Checklist Viewer (renders contract's "plan" array shape) */}
      {isPlanModalOpen && activePlan && (
        <div className="modal-overlay" onClick={() => setIsPlanModalOpen(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '1rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <Cpu size={24} color="var(--primary-light)" />
                <div>
                  <h2 style={{ fontSize: '1.35rem', fontWeight: 700 }}>Mission Plan Checklist</h2>
                  <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    Generated by MissionPlannerAgent &bull; Order #{activeRequestId?.slice(0, 8)}
                  </span>
                </div>
              </div>
              <button
                style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}
                onClick={() => setIsPlanModalOpen(false)}
              >
                <X size={20} />
              </button>
            </div>

            {/* Contract Output Metadata */}
            <div style={{ display: 'flex', justifyContent: 'space-between', background: 'rgba(15, 23, 42, 0.6)', padding: '0.75rem 1rem', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border-subtle)', marginBottom: '1.25rem', fontSize: '0.825rem' }}>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>dispatchRequestId: </span>
                <span style={{ fontFamily: 'monospace', color: 'var(--primary-light)', fontWeight: 600 }}>{activePlan.dispatchRequestId}</span>
              </div>
              <div>
                <span style={{ color: 'var(--text-muted)' }}>createdAt: </span>
                <span>{new Date(activePlan.createdAt).toLocaleString()}</span>
              </div>
            </div>

            <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
              Execution checklist rendered directly from the contract's <code style={{ color: 'var(--primary-light)' }}>plan</code> array:
            </p>

            {/* Render contract's "plan" array shape */}
            <div className="checklist-timeline">
              {activePlan.plan.map((step) => (
                <div key={step.stepNumber} className="checklist-step-item">
                  <div className="step-badge-number">{step.stepNumber}</div>
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.35rem' }}>
                      <span style={{ fontWeight: 600, fontSize: '0.95rem' }}>{step.stepName}</span>
                      <span className="badge" style={{ background: 'rgba(245, 158, 11, 0.15)', color: '#fbbf24', border: '1px solid rgba(251, 191, 36, 0.3)' }}>
                        {step.status}
                      </span>
                    </div>

                    {step.assignedAgent && (
                      <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.775rem', color: 'var(--text-muted)' }}>
                        <Radio size={12} color="var(--primary-light)" />
                        Assigned: <strong style={{ color: 'var(--text-main)' }}>{step.assignedAgent}</strong>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '1.75rem' }}>
              <button className="btn btn-primary" onClick={() => setIsPlanModalOpen(false)}>
                Close Checklist
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
